### ISSUE TITLE
the code of the Model-Based Image Signal Processors via Learnable Dictionaries

### ISSUE THREAD

**Issue by developWmark** [mv-lab/mv-lab.github.io#1]
hello ,Marcos V. Conde. I'm mark and i'm a master of Computer Science.I'm a big fan of your work about the work.could you please share codes of the model.

**Comment by mv-lab** [comment]
@developWmark please contact me via email [marcos.conde-osorio@uni-wuerzburg.de](mailto:marcos.conde-osorio@uni-wuerzburg.de) and check https://github.com/mv-lab/AISP
